### ISSUE TITLE
 I thought this was the Open AI Chat GPT 4 app for Mac. Requesting Refund

### ISSUE THREAD

**Issue by calebmills99** [Writer-Sonic/AI-writer#11]
I asked for a refund through the app store and was denied on three charges of 6.99. I thought this was the Open AI Chat GPT 4 app for Mac. I already pay Open AI for this service. So I mistakenly paid for another app that offers the same service. I did not realize this. If I had, I would not have downloaded it.  I requested a refund and it was refused on all three charges. Apple told me to contact the developer. I really would like a refund please.

**Comment by calebmills99** [comment]
![Screenshot 2024-04-21 at 4 45 17 PM](https://github.com/Writer-Sonic/AI-writer/assets/161272723/53b47896-7b68-4687-a7e7-20f51704445a)

**Comment by calebmills99** [comment]
That ChatGPT in bold at the top makes it seem like it is the app offered by Open AI. I wonder how many people download it and end up paying for both services inadvertently. Have you guys thought about making it a bit more clear that you are not Open AI?

**Comment by aryan1107** [comment]
Hi have made the requested changes!
