### ISSUE TITLE
Payment issue not credited to account

### ISSUE THREAD

**Issue by CRL71** [Writer-Sonic/AI-writer#2]
I have paid $35.99 under my wife's name for more words and the money has come out of our account but the words have not been credited to my account. 
![image](https://user-images.githubusercontent.com/124041109/215930431-06aef974-bbe4-411e-8691-2730f6943063.jpeg)
![image](https://user-images.githubusercontent.com/124041109/215930457-3c860ec2-2d6e-460c-99cd-a8829726b2cf.jpeg)

**Comment by aryan1107** [comment]
Hi there sorry for super late response I just didn't get any notification. Can you send how much word used it is showing?
