### ISSUE TITLE
How do I sign in with my Premium from App Store to Macbook

### ISSUE THREAD

**Issue by benphi321** [Writer-Sonic/AI-writer#4]
Hello, I have the paid premium version of "AI Chat - Writing Chatbot" from Vulcan on my phone from App Store. Is that the same thing as this app?  I just don't want to pay twice if I don't have to. Please help? Thanks!

**Comment by aryan1107** [comment]
Hi if you use my app it should work but if you have paid for some other app then you can't.

**Comment by aryan1107** [comment]
I am marking this as resolved please let me know
