### ISSUE TITLE
Paid premium but not working

### ISSUE THREAD

**Issue by ash-pow** [Writer-Sonic/AI-writer#5]
It keeps telling me to update my app on my macbook, but the app is already updated. It wont give me any response besides "Please update your APP! and get better version of me where you can also create your own AI" or "Sorry I faced some issues..please try again"

**Comment by aryan1107** [comment]
Hi sorry to hear that. Can you send this picture from App Store as attached
here which shows that you all is updated?
Because I know many people are using the latest version they don’t have any
issues.
The new version generates much more content.

**Comment by aryan1107** [comment]
I am marking this as resolved please let me know
