### ISSUE TITLE
App closing upon opening

### ISSUE THREAD

**Issue by csumner720** [Writer-Sonic/AI-writer#7]
I click on the app and it opens and immediately closes. I have updated my software, deleted the app several times and restarted my computer. Still is not working

**Comment by christophekerkhofs** [comment]
I am having the same problem.  It only starten happening since the last version: 6.7.4

I am working on MacOS BigSur v11.7.10

Attached you can find all the logging I could find.

[Crashlog.txt](https://github.com/Writer-Sonic/AI-writer/files/13047124/Crashlog.txt)
![Crashlog2](https://github.com/Writer-Sonic/AI-writer/assets/8582137/fd8e587f-4815-4f2d-abfa-4a7fc4ee8074)

**Comment by csumner720** [comment]
I have the same operating systems

**Comment by aryan1107** [comment]
Hi thanks for the info can you tell me at what stage does it crash for
example clicking at certain button / or else/ opening something?

Best
Arya

**Comment by csumner720** [comment]
It opens for less than a second and then shuts off

**Comment by aryan1107** [comment]
Alright Looking into this for now please use web version app.chat-guru.com

**Comment by csumner720** [comment]
thank you

**Comment by aryan1107** [comment]
Have added new update Can you download this version and let me know if it works?
https://apps.apple.com/us/app/chatg-unlimited-ai-chat-bot/id6443925235
Thanks:)

**Comment by csumner720** [comment]
It Is still crashing.

**Comment by csumner720** [comment]
System Integrity Protection: enabled

Crashed Thread:        5  Dispatch queue: com.google.firebase.firestore

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1260]

**Comment by aryan1107** [comment]
Another update is added please can you try again and confirm have added download link? Really sorry for inconvenience. 

 https://apps.apple.com/us/app/chatg-unlimited-ai-chat-bot/id6443925235

**Comment by christophekerkhofs** [comment]
Sorry,
We’re still facing the same issue. Do you need a new crash report?

**Comment by aryan1107** [comment]
Yes can you send me please I am trying to figure out as others are able to use it.

**Comment by christophekerkhofs** [comment]
Is this sufficient?

[Crashlog 241024-2.txt](https://github.com/Writer-Sonic/AI-writer/files/13111115/Crashlog.241024-2.txt)
[Crashlog 241024.txt](https://github.com/Writer-Sonic/AI-writer/files/13111117/Crashlog.241024.txt)

**Comment by csumner720** [comment]
I just downloaded the new version this morning and it still crashes.

**Comment by aryan1107** [comment]
@christophekerkhofs @csumner720 Can you download once again and check here is the link: https://apps.apple.com/us/app/chatg-unlimited-ai-chat-bot/id6443925235

I downgraded some of the sdk's to older version so far no crash has been observed.

**Comment by csumner720** [comment]
Its working. Thank you so much!!!

**Comment by aryan1107** [comment]
The latest version is 6.7.15 not 12 please use the link to update it https://apps.apple.com/us/app/chatg-unlimited-ai-chat-bot/id6443925235

**Comment by christophekerkhofs** [comment]
Thank you,  that version works!
