### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Rambo197** [Writer-Sonic/AI-writer#8]
My app crashed as well, so I've been using the web version instead but now its not wanting to work for me on that, it keeps popping up this error:

Error: ClientException: XMLHttpRequest error., uri=https://us-central1-ai-writer-a4f99.cloudfunctions.net/chatgptv3-withfreeFlutterV1

can you please fix

**Comment by aryan1107** [comment]
This is an issue with the internet. Make sure you are not being blocked, in some areas like China app is blocked and people use vpn.

**Comment by Rambo197** [comment]
Im in texas of the united states, does any blocking happen over here?? Or
is it just the internet connection

**Comment by Rambo197** [comment]
how do i see if its being blocked??

**Comment by Rambo197** [comment]
it says the following below:
Crashed Thread:        20  Dispatch queue: com.google.firebase.firestore

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [61803]

**Comment by aryan1107** [comment]
Can you update the app and try again. Here is the link

https://apps.apple.com/ca/app/chatg-unlimited-ai-chat-bot/id6443925235
